server:
  port: 8099

spring:
  application:
    name: profile-service

  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root
    url: jdbc:postgresql://localhost:5431/projecthub
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: false
  profiles:
    active: dev
  data:
    redis:
      host: localhost
      port: 6379

logging:
  file:
    path: ./logs
  level:
    root: info
    org:
      springframework:
        web: warn
      hibernate: error
    web: warn


springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

auth:
  jwt:
    secret: a3dwap2awpokDopwad

eureka:
  client:
    service-url:
        defaultZone: http://localhost:8761/eureka/
  instance:
    preference-ip-address: true

