server:
  port: 8095

spring:
  application:
    name: email-service

  datasource:
    url: jdbc:postgresql://postgres:5432/projecthub
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: false
  profiles:
    active: dev
  mail:
    host: smtp.gmail.com
    port: 587
    username: ivanemail1234567890@gmail.com
    password: xdux kmya woic vnlf
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connection timeout: 10000
          timeout: 10000
          write timeout: 10000
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false
    debug: true

  kafka:
    topic:
      send-email: "email-send"


#  data:
#    redis:
#      host: redis
#      port: 6379

logging:
  file:
    path: ./EmailService/logs
  level:
    root: info
    org:
      springframework:
        web: warn
      hibernate: error
    web: warn

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

auth:
  jwt:
    secret: a3dwap2awpokDopwad


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preference-ip-address: true
