server:
  port: 8090

spring:
  application:
    name: management-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5431/projecthub
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false

  kafka:
    topic:
      send-email: "email-send"
logging:
  level:
    root: info
    org:
      springframework:
        web: warn
      hibernate: error
    web: warn
  file:
    path: ./ManagementService/logs

auth:
  jwt:
    secret: a3dwap2awpokDopwad


springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preference-ip-address: true